eureka:
  instance:
    hostname: localhost
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka

products:
  message: "Hey Welcome to MicroServices Config Server"
  contactDetails:
    name: "Chinmay Rele"
    email: "{cipher}42f02f7745f863547e333af6c5f4ae9c40edf36f44934898735181878ff08db97986c837a9c36967714495dd56b4178c"
  onCallSupport:
    - 9078563412
    - 9404372648


orders:
  message: "Hey Welcome to MicroServices Config Server of Order"
  orderContactDetails:
    name: "Chinmay Rele - ORDER"
    email: "{cipher}42f02f7745f863547e333af6c5f4ae9c40edf36f44934898735181878ff08db97986c837a9c36967714495dd56b4178c"
  onCallSupport:
    - 9078563412
    - 9404372648
