spring:
  application:
    name: Config-DEV
eureka:
  instance:
    hostname: localhost
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka

products:
  message: "Hey Welcome to MicroServices Development Config Server"
  contactDetails:
    name: "Vaishnavi Adhau Developer"
    email: "{cipher}0a35482af90d85ef79a33cf9cf6d4bc6fba54fc2ad48bc77fba7185468fc3d40869ceb70c0e081fc8de70b6845d8e16e"
  onCallSupport:
    - 8079685746
    - 3554678534
