spring:
  application:
    name: Config-User-PROD

eureka:
  instance:
    hostname: localhost
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka

build:
  version: "1.0"

user-profiles:
  message: "Hey Welcome to MicroServices Config Server of User Profile PROD"
  userContactDetails:
    name: "Shubhangi Tayade- PROD"
    email: "{cipher}9fd6015eb70d36cc3196626e0bda9ac0fb4dca675f8f3f88cdda2f42915c5857661bcc7ea1a0a63dded6306821628f37"
  onCallSupport:
    - 9078563412
    - 9404372648
